# Generated by Django 6.1 on 2026-08-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/')),
                ('caption', models.CharField(blank=True, help_text='Optional text shown over the image.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
